### ISSUE TITLE
Question about ChEMBL34 Postgres dump

### ISSUE THREAD

**Issue by baoilleach** [chembl/chembl_data_issues#13]
When I import the Postgres datadump from https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/chembl_34_postgresql.tar.gz, every table seems fine except that there is one empty table, namely *component_domains*. The equivalent ChEMBL33 import has data in this table. Is this data definitely in the postgres dump? (Or is there a problem with our import?)

**Comment by eloyfelix** [comment]
Apologies for the delayed response. There is missing data in the dumps; your import is fine. We're investigating the causes.

**Comment by eloyfelix** [comment]
Quick update: We'll append a file to our downloads folder including the data for `component_domains` table as soon as we have it available.

**Comment by eloyfelix** [comment]
Please find the data for the `component_domains` table in the following [link](https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/COMPONENT_DOMAINS.tsv)

Many thanks for reporting this btw!
