### ISSUE TITLE
CHEMBL2106323

### ISSUE THREAD

**Issue by phytophreak** [chembl/chembl_data_issues#14]
Hello,

I just had a look at the latest data dump from ChEMBL (version 34) and discovered a small issue:

[CHEMBL2106323](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2106323/) does have structure information assigned, but it's parent compound [CHEMBL5314358](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL5314358/) does not. Is this intended?

Kind regards,
Bernhard

**Comment by Emma-Manners** [comment]
Thanks for raising this issue. 

ChEMBL doesn’t show structures for mixtures, unless the ratio of components is defined. Anhydrous lactose is a mixture of the alpha and beta form. Although the beta form may be dominant, we have removed the structure in line with our rules and to be consistent with the USP dictionary.

Any further queries, please get in touch.
