### ISSUE TITLE
Duplicate cell line labels

### ISSUE THREAD

**Issue by janelomax** [chembl/chembl_data_issues#15]
Hi - you have 4 different Cell Line entries for "Bone marrow cell" - CHEMBL4295339, CHEMBL4295340, CHEMBL4295341, CHEMBL3833841

Looks like these are from different species, would you consider renaming them e.g. "human bone marrow cell"

**Comment by Emma-Manners** [comment]
Thanks for your message and suggestion. 

You’re correct, we do have several entries for the cell type ‘Bone marrow cell’ and these reflect different (or unknown) species. 

We’d need to review all cells (and not just bone marrow cell) if we were to update cell names to include the species. 

However, having “human” in the cell name would duplicate the species information already available in the organism field and would meant that the “same” cells would have multiple names. At the moment, we have no plans to rename these cells but we’ll discuss further within the team.
