### ISSUE TITLE
Discrepancy between max phase classification and Indications content for CHEMBL2362016

### ISSUE THREAD

**Issue by EPetsalaki** [chembl/chembl_data_issues#4]
Hello, 

The max phase stated in the 'Name and classification' card for compound CHEMBL2362016 is 0, while there is a list of clinical trials in the 'Indications' card that goes up to phase 4. 
The name is also missing; quick wikipedia search says that it is arsenic trioxide in its liquid and gas form (below 800 C). 

Thanks!

**Comment by Emma-Manners** [comment]
Thanks for raising this issue. I've checked and it seems to be resolved.
