### ISSUE TITLE
nonunique CHEMBLIDs

### ISSUE THREAD

**Issue by shamsaraj** [chembl/chembl_data_issues#9]
Hi, these two CHEMBLIDs refer to the same UniProt entry; CHEMBL2065 and CHEMBL2364670

**Comment by Emma-Manners** [comment]
Thanks for raising this issue. 
For protein targets, we link to UniProt accessions.
This target - https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL2364670/- is a broad target with the organism recorded as 'Bacteria'. It's used to map bioactivity data where the target organism is poorly defined. 
However, we still link UniProt accessions to these broad targets but UniProt entries are associated with a specific organism, in this case _E. coli_, and therefore the same UniProt accession has been used for both the _E.coli_ protein and the 'Bacterial' protein. 
The target organism can be used to differentiate the targets.
